chore(oep-cli): regenerate rendered/openedge-cli

diff --git a/frameworks/oep-installer-cli/rendered/openedge-cli b/frameworks/oep-installer-cli/rendered/openedge-cli
--- a/frameworks/oep-installer-cli/rendered/openedge-cli
+++ b/frameworks/oep-installer-cli/rendered/openedge-cli
@@ -1912,11 +1912,20 @@ ensure_ip () {
 
 # ensure ports are open
 ensure_ports_open () {
-  local ports="$1"
+  local ports="$1"; shift
   for port in $ports; do
-    ensure_sudo lsof -i TCP:$port > /dev/null 2>&1 || continue
-    "${@:2}" || true
-    ensure_sudo lsof -i TCP:$port > /dev/null 2>&1 || continue
+    if command -v ss > /dev/null; then
+      [ -n "$(ensure_sudo ss -Hltn "sport = :$port")" ] || continue
+      "$@" || true
+      [ -n "$(ensure_sudo ss -Hltn "sport = :$port")" ] || continue
+    elif command -v lsof > /dev/null; then
+      ensure_sudo lsof -nP -i TCP:$port -s TCP:LISTEN > /dev/null 2>&1 || continue
+      "$@" || true
+      ensure_sudo lsof -nP -i TCP:$port -s TCP:LISTEN > /dev/null 2>&1 || continue
+    else
+      echo "Missing ss or lsof" 1>&2
+      return 1
+    fi
     echo "TCP port $port is occupied" 1>&2
     return 3
   done
@@ -2068,6 +2077,12 @@ ensure_trap() {
 # apt with apt update executed only once
 ensure_apt () {
   local no_proxy1=$(echo ${no_proxy:-$NO_PROXY} | tr ',' '\n' | grep -v -E '^[.]?intel.com$' | tr '\n' ',')
+
+  while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; do
+    echo "Waiting for apt/unattended-upgrades to finish..." 1>&2
+    sleep 5
+  done
+
   case "$1" in
   update)
     # apt-get update got executed only once unless -y is specified
@@ -3897,8 +3912,7 @@ configure_multimodal_weld_defect_detection () {
   pipeline_config="$source_dir/configs/dlstreamer-pipeline-server/config.json"
   pipeline_request="$source_dir/configs/dlstreamer-pipeline-server/pipeline-request-cpu.json"
   selected_device_file="$source_dir/.oep_device"
-  ui_port=3000
-  used_ports="$ui_port 3478"
+  used_ports=(3000 3478 8010 8200)
 }
 
 generate_multimodal_weld_defect_detection_username () {
@@ -4054,7 +4068,7 @@ debian_90_start_multimodal_weld_defect_detection () {
   cd "$source_dir"
   make up
 
-  echo "@@HIGHLIGHT URL: https://$(ensure_ip):$ui_port"
+  echo "@@HIGHLIGHT URL: https://$(ensure_ip):${used_ports[0]}"
   echo "@@HIGHLIGHT Grafana login: $(multimodal_weld_defect_detection_env_value VISUALIZER_GRAFANA_USER)/$(multimodal_weld_defect_detection_env_value VISUALIZER_GRAFANA_PASSWORD)"
   echo "@@HIGHLIGHT device: $(current_multimodal_weld_defect_detection_device)"
 }
