unit (#3369)
Co-authored-by: x.y <x@y>

diff --git a/frameworks/oep-installer-cli/common/linux/ensure_disk_size b/frameworks/oep-installer-cli/common/linux/ensure_disk_size
--- a/frameworks/oep-installer-cli/common/linux/ensure_disk_size
+++ b/frameworks/oep-installer-cli/common/linux/ensure_disk_size
@@ -1,11 +1,11 @@
 
 # check disk space
 ensure_disk_size () {
-  local disk_size=$1            # in MB
+  local disk_size=$1            # in MB (1000000 bytes)
   local disk_path="${2:-$HOME}" # optional disk path
-  local disk_avail=$(df -h --output=avail "$disk_path" | awk '/[0-9]T/{a=$1*1000000}/[0-9]G/{a=$1*1000}/[0-9]M/{a=$1*1}/[0-9]K/{a=$1/1000}END{print int(a)}')
+  local disk_avail=$(df -B1 --output=avail "$disk_path" | awk 'NR==2{print int($1/1000000)}')
   if [ "$disk_size" -gt "$disk_avail" ]; then
-    echo "Not enough disk space: required ${disk_size}MiB and available ${disk_avail}MiB"
+    echo "Not enough disk space: required ${disk_size} MB and available ${disk_avail} MB" 1>&2
     return 3
   fi
 }
